on: push
name: laravel
jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.0
 
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: tim3_app
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
        
    - name: Install composer dependencies
      run: |
        composer update
        composer install --no-scripts
 
    - name: Prepare Laravel Application
      run: |
        php artisan key:generate
 
    - name: Run Testsuite
      run: vendor/bin/phpunit tests/
